package Responses;
/**
 * A response to a request to create a new game
 */
public class CreateGameResponse extends Response {
    /**
     * Check that the response code is one that is used by this response type
     * @param responseCode
     */
    private void checkValidCode(int responseCode) {
        if (responseCode == 403) {
            System.out.println("Wrong response code; this is not used for CreateGame response");
            System.exit(0);
        }
    }
    /**
     * If a constructor is only meant to be used for an error code, this makes sure that
     * the response code is indeed an error code
     * @param responseCode
     */
    private void checkNot200(int responseCode) {
        if (responseCode == 200) {
            System.out.println("Error: CreateGame response success must specify gameID");
            System.exit(0);
        }
    }
    /**
     * Calls constructor in parent class that generates the default message for the given
     * error code. Can only be used with error codes.
     * @param responseCode
     */
    public CreateGameResponse(int responseCode) {
        super(responseCode);
        checkNot200(responseCode);
        checkValidCode(responseCode);
    }
    /**
     * Constructor for generating custom error messages (only used with error codes)
     * @param responseCode
     * @param message The custom message
     */
    public CreateGameResponse(int responseCode, String message) {
        super(responseCode, message);
        checkNot200(responseCode);
        checkValidCode(responseCode);
    }
    /**
     * The constructor called for a response to a successful request. If request was not
     * successful, the server creator is notified and the default error message is generated
     * @param responseCode
     * @param gameID The game ID generated by the server for the new game
     */
    public CreateGameResponse(int responseCode, int gameID) {
        super(responseCode);
        checkValidCode(responseCode);
        if (responseCode != 200) {
            System.out.println("gameID not necessary for a failure response");
            return;
        }
        this.gameID = gameID;
    }

    public int getID() {
        return gameID;
    }
    /**
     * The ID of the new game
     */
    private Integer gameID;
    private Integer index;
}
